### ISSUE TITLE
Function of ctr.pt and lva.pt?

### ISSUE THREAD

**Issue by minghong-X** [tsujuifu/pytorch_clva#3]
What`s the function of the ctr.pt and lva.pt?
In inference.py, u use the clva_dtd.pt! And if i want to use this code,how do i train the model(instead of using clva_dtd.pt)
Thanks for your answer!

**Comment by tsujuifu** [comment]
**clva_dtd.pt** is our final checkpoint.
You can first run _train_lva.py_ for **lva.pt** and then _train_ctr.py_ for **ctr.pt**.

**Comment by minghong-X** [comment]
Thanks for your answer!
About how to generate **ctr.pt** and **lva.pt**, I can see that from your code.
But the **clva_dtd.pt** is a download file. And how I generate this(**clva_dtd.pt**)?
By the way, i found the **lva.pt** and **clva_dtd.pt** has the same network structure.

**Comment by tsujuifu** [comment]
**clva_dtd.pt** can be seen as **ctr.pt**, which is the final LDAST checkpoint.

**lva.pt** and **ctr.pt** share the same architecture, but follow a different training strategy.

**Comment by minghong-X** [comment]
Thank u! Get it!~~~
